version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=merchant
      - POSTGRES_DB=galaxy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@e.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '*:5432:galaxy:merchant:pass' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - ${PGADMIN_PORT}:80
    profiles:
      - local

  portainer:
    restart: always
    image: portainer/portainer
    ports:
      - ${PORTAINER_PORT}:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    profiles:
      - local

volumes:
  portainer_data:
  postgres:
  pgadmin:
